### ISSUE TITLE
Not able to use global CSS styles

### ISSUE THREAD

**Issue by erfan-ilyas** [rupok/essential-addons-for-elementor-lite#272]
Hello,

Thanks for building a superb plugin.

I have one major issue that preventing me using this plugin for my templates.

I am a professional elementor Template developer and re-use my designed blocks.

Currently the plugin css is output is something like this:

```CSS
.elementor-1851 .elementor-element.elementor-element-0187ae7 .eael-creative-button {
    color: #ffffff;
    background-color: #333333;
}
```

This overrides my base template styles:

I have to manually select the colors for each and every element.

However when I use Elementor original Elements I don't find this issue.

This is the original sample CSS that Elementor generates
```CSS
.elementor-widget-button a.elementor-button, .elementor-widget-button .elementor-button {
    font-family: "Poppins", Sans-serif;
    font-weight: 500;
    background-color: #aac9c3;
}
```

I can easily override my styles from my base theme Global CSS.

Can you remove all those dynamic css path that this plugin generates?

Kind Regards,
Erfan
