### ISSUE TITLE
Uncaught Error: Class 'Essential_Addons_Elementor\\Classes\\Bootstrap' not found

### ISSUE THREAD

**Issue by one-pieces** [rupok/essential-addons-for-elementor-lite#311]
I use docker-compose to run wordpress, but it could not be accessed when I up the container.

<img width="979" alt="Screen Shot 2019-05-23 at 7 36 31 PM" src="https://user-images.githubusercontent.com/13073614/58249674-186cee00-7d92-11e9-8674-16bc011129b1.png">

And `docker-compose logs` shows the follows.

<img width="1440" alt="Screen Shot 2019-05-23 at 7 29 21 PM" src="https://user-images.githubusercontent.com/13073614/58249340-2ff7a700-7d91-11e9-9732-95ae5db8f6ad.png">

`docker-compose.yml`
```
version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - "8002:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
#volumes:
#  db_data: {}
#  src: {}

```

wordpress: 5.2.1
EAE version: 3.0.0
